// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkF7kjoAGFunFs5xXHJviGz4w1PKolzmA',
    appId: '1:355730024898:web:9e7b194b51ed4b46b70e5b',
    messagingSenderId: '355730024898',
    projectId: 'lit-library-d2a79',
    authDomain: 'lit-library-d2a79.firebaseapp.com',
    storageBucket: 'lit-library-d2a79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6Nm1RMdPrpOsJYS7-UeAcDDbmmQDv8o',
    appId: '1:355730024898:android:db5d247dbf7b58bcb70e5b',
    messagingSenderId: '355730024898',
    projectId: 'lit-library-d2a79',
    storageBucket: 'lit-library-d2a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVk4t2X-D5tYAlmpBMJhL2IRtExAgY0to',
    appId: '1:355730024898:ios:cdd84026c674df0db70e5b',
    messagingSenderId: '355730024898',
    projectId: 'lit-library-d2a79',
    storageBucket: 'lit-library-d2a79.appspot.com',
    iosBundleId: 'com.example.litLibraryy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVk4t2X-D5tYAlmpBMJhL2IRtExAgY0to',
    appId: '1:355730024898:ios:cdd84026c674df0db70e5b',
    messagingSenderId: '355730024898',
    projectId: 'lit-library-d2a79',
    storageBucket: 'lit-library-d2a79.appspot.com',
    iosBundleId: 'com.example.litLibraryy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkF7kjoAGFunFs5xXHJviGz4w1PKolzmA',
    appId: '1:355730024898:web:ac4fca7a9a4a7790b70e5b',
    messagingSenderId: '355730024898',
    projectId: 'lit-library-d2a79',
    authDomain: 'lit-library-d2a79.firebaseapp.com',
    storageBucket: 'lit-library-d2a79.appspot.com',
  );
}
